// 專案層流程 — framework/02 §2.1
export default {
  id: "glados_project_flow",
  title: "專案層流程",
  subtitle: "每個專案跑一次；橘色六角形是人工關卡",
  direction: "DOWN",
  nodes: [
    { id: "P0", tag: "P0", title: "專案啟動", sub: "定範圍、T0、起點、知識庫快照" },
    { id: "G0", kind: "gate", title: "G0 啟動核准" },
    { id: "P1", tag: "P1", title: "基線建立", sub: "確認起點能 build、能跑，留下對照基準" },
    { id: "P2", tag: "P2", title: "差異分析", sub: "範圍 CR → code → 切成模組" },
    { id: "G1", kind: "gate", title: "G1 範圍核准" },
    { id: "P3", tag: "P3", title: "架構與介面", sub: "介面合約、記憶體預算" },
    { id: "G2", kind: "gate", title: "G2 架構審查" },
    { id: "M", tag: "M1–M7", title: "每個模組各跑一次", sub: "見模組流程圖" },
    { id: "P4", tag: "P4", title: "整合", sub: "合入所有模組，驗端到端 boot flow" },
    { id: "P5", tag: "P5", title: "全量驗收", sub: "regression、靜態分析、安全審查" },
    { id: "G3", kind: "gate", title: "G3 最終交付核准" },
    { id: "P6", tag: "P6", title: "交付", sub: "release／ROM tapeout" },
    { id: "P7", tag: "P7", title: "回寫", sub: "知識庫、規則、skill、hook" },
    { id: "G4", kind: "gate", title: "人確認回寫提案" },
  ],
  edges: [
    ["P0", "G0"], ["G0", "P1"], ["P1", "P2"], ["P2", "G1"], ["G1", "P3"], ["P3", "G2"], ["G2", "M"],
    ["M", "P4"], ["P4", "P5"], ["P5", "G3"], ["G3", "P6"], ["P6", "P7"], ["P7", "G4"],
    ["P2", "P0", "資訊不足", "back"],
    ["P3", "P2", "範圍有誤", "back"],
    ["M", "P3", "介面衝突", "back"],
    ["P4", "M", "失敗：回對應的模組", "back"],
    ["P5", "M", "失敗：回對應的模組", "back"],
    ["P6", "P5", "交付內容和核准版本不符", "back"],
  ],
};
