// 模組流程 — framework/02 §2.3
export default {
  id: "glados_module_flow",
  title: "模組流程",
  subtitle: "每個模組各跑一次 M1–M7；其他問題一律交給 R 失敗分類",
  direction: "DOWN",
  nodes: [
    { id: "IN1", kind: "ext", title: "P3 展開，或需求變更" },
    { id: "M1", tag: "M1", title: "需求釐清", sub: "寫成有編號的 spec 條目" },
    { id: "WAIT", kind: "wait", title: "等待外部回覆", sub: ["登記待確認事項", "設定允許時寫進 Jira，否則由人轉問", "答案回來再接續"] },
    { id: "H1", kind: "gate", title: "H1 需求核准" },
    { id: "IN2", kind: "ext", title: "bug 型 CR" },
    { id: "M2", tag: "M2", title: "驗收定義", sub: ["驗收合約、case、判別能力證據", "先完成獨立審查與工具檢查"] },
    { id: "Q2", kind: "decision", title: "驗收合約有新增或變更嗎？" },
    { id: "H2", kind: "gate", title: "H2 驗收合約核准" },
    { id: "TB", kind: "rule", title: "建立測試基準，M2 完成", sub: "串接層核對目前版本的證據與合約核准" },
    { id: "IN3", kind: "ext", title: "介面或記憶體預算變更" },
    { id: "M3", tag: "M3", title: "實作計畫", sub: ["另一個 session 審查計畫", "↻ 審查有阻擋項目：修計畫重審，最多 3 輪"] },
    { id: "M4", tag: "M4", title: "實作與 build", sub: ["只改計畫列出的檔案", "↻ build 失敗或超預算：重做，最多 3 輪"] },
    { id: "M5", tag: "M5", title: "驗證", sub: "跑驗收合約的必要 case" },
    { id: "M6", tag: "M6", title: "獨立審查", sub: "另一個執行者審查 diff" },
    { id: "M7", tag: "M7", title: "完成交接", sub: "串接層核對全部紀錄" },
    { id: "P4", kind: "ext", title: "P4 整合（專案層）" },
    { id: "R", kind: "rule", title: "R 失敗分類", sub: ["決定退回哪裡（見失敗分類圖）", "任何一站回報輸入不足也交給它"] },
  ],
  edges: [
    ["IN1", "M1"],
    ["M1", "WAIT", "有問題要問外部", "wait"],
    ["WAIT", "M1", "", "wait"],
    ["M1", "H1"], ["H1", "M2"], ["IN2", "M2"], ["M2", "Q2"],
    ["Q2", "H2", "有"], ["H2", "TB", "核准"],
    ["H2", "M2", "不核准：修正並重檢", "back"],
    ["Q2", "TB", "沒有，沿用有效合約核准"], ["TB", "M3"],
    ["IN3", "M3"],
    ["M3", "M4"], ["M4", "M5"],
    ["M5", "M6", "必要 case 全部 PASS"],
    ["M6", "M7", "沒有未處置的阻擋項目"],
    ["M7", "P4"],
    ["M2", "R", "spec 條目轉不成 case、\n平台觀察不到", "back"],
    ["M3", "R", "需求或架構爭議", "back"],
    ["M4", "R", "需要改計畫以外的檔案", "back"],
    ["M5", "R", "case FAIL、環境錯誤、\n驗證缺口", "back"],
    ["M6", "R", "需要修正", "back"],
    ["M7", "R", "紀錄不齊或對不上目前版本", "back"],
  ],
};
