// R 失敗分類的去處 — framework/04 §4.5
export default {
  id: "glados_failure_routing",
  title: "R 失敗分類的去處",
  subtitle: "橘色的去處需要人；灰色的不需要",
  direction: "RIGHT",
  uniform: false,
  layerSpacing: 70,
  nodes: [
    { id: "IN", kind: "ext", title: "M2–M7、P4、P5", sub: "發現問題" },
    { id: "R", kind: "rule", title: "R 失敗分類", sub: ["依規則判斷類型", "判不出來時派一次獨立分析參考"] },
    { id: "D1", kind: "ext", title: "回 M4 實作與 build", sub: "計入輪數" },
    { id: "D2", kind: "ext", title: "回 M3 實作計畫" },
    { id: "D3", kind: "ext", title: "回 M2 驗收定義", sub: "在合約內修正" },
    { id: "D4", kind: "human", title: "回 M2，經 H2 核准", sub: "需求也變就先回 M1" },
    { id: "D5", kind: "human", title: "回 M1，經 H1 核准" },
    { id: "D6", kind: "human", title: "回 P3，經 G2 核准" },
    { id: "D7", kind: "ext", title: "從最早過期的那一站重走" },
    { id: "D8", kind: "human", title: "交給人" },
  ],
  edges: [
    ["IN", "R"],
    ["R", "D1", "code 錯"],
    ["R", "D2", "計畫不夠用"],
    ["R", "D3", "測試實作錯"],
    ["R", "D4", "驗收標準要改"],
    ["R", "D5", "spec 缺口或矛盾"],
    ["R", "D6", "介面衝突"],
    ["R", "D7", "交接紀錄過期或不齊"],
    ["R", "D8", "環境問題、驗證缺口、\n連續 3 輪同樣失敗"],
  ],
};
